# Assisted by watsonx Code Assistant 
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.
# Get java_home from user
$javahome = Read-Host "Enter the JAVA_HOME location"

# Print the javahome variable
Write-Host "JAVA_HOME is: $javahome"
Write-Host

# Clone git repo
Write-Host "Cloning odm-tomcat git repo https://github.com/eddycaballeroibm/odm-tomcat.git"
git clone https://github.com/eddycaballeroibm/odm-tomcat.git
Write-Host
Write-Host

# Enter the repo
Write-Host "Changing directory to the odm-tomcat repo"
cd odm-tomcat/apache-tomcat-9.0.84
Write-Host
Write-Host

# Set the CATALINA_HOME env variable
$catalinahome = (Get-Location).Path
Write-Host "The current directory is: $catalinahome"
Write-Host "CATALINA_HOME will be set to: $catalinahome"
Write-Host
Write-Host

#append CATALINA_HOME to cataline.bat file
$filePath = (Get-Location).Path + "\bin\catalina.bat"
$catalinalineNumber =118
$catalinatext = "set CATALINA_HOME=$catalinahome"
$content = Get-Content $filePath
$content[$catalinalineNumber - 1] += $catalinatext
Set-Content $filePath -Value $content
Write-Host "CATALINA_HOME added to catalina.bat successfully."

#append JAVA_HOME to cataline.bat file
$javalineNumber =119
$javatext = "set JAVA_HOME=$javahome"
$content = Get-Content $filePath
$content[$javalineNumber - 1] += $javatext
Set-Content $filePath -Value $content
Write-Host "JAVA_HOME added to catalina.bat successfully."

#append JRE_HOME to cataline.bat file
$jrelineNumber =120
$jretext = " set JRE_HOME=$javahome"
$content = Get-Content $filePath
$content[$jrelineNumber - 1] += $jretext
Set-Content $filePath -Value $content


Write-Host "JRE_HOME added to catalina.bat successfully."
Write-Host
Write-Host
Write-Host "Tomcat server installed successfully."